name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt-get update
        sudo apt-get -y install cuda-toolkit-12-4

    - name: Build GPU Monitor
      run: |
        cd gpu_monitors
        make
    
    - name: Build Matrix Multiply
      run: |
        cd gpu_test
        make

    - name: Check Compilation
      run: |
        if [ -f "gpu_monitors/gpu_monitor.cpp" ] && [ -f "gpu_test/matrix_multiply.cu" ]; then
          echo "Compilation check passed"
        else
          echo "Compilation check failed"
          exit 1
        fi
